/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dbproject;

import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Andrtea
 */
public class Insert extends javax.swing.JFrame {

    /**
     * Creates new form Inserimento
     */
    public Insert() {
        initComponents();
        setLocationRelativeTo(null);
        jTable2.setShowGrid(false);
        jTable1.setShowGrid(false);
        jTable2.setVisible(true);
        jTable1.setVisible(true);
        jText1.setVisible(false);
        jText2.setVisible(false);
        jText3.setVisible(false);
        jText4.setVisible(false);
        jText5.setVisible(false);
        jText6.setVisible(false);
        box.setVisible(false);
        jComboBoxTipo.setVisible(false);
        try {
            String order="SQUADRA";
            rs=DBproject.ricAllGioc(this, order);
            jTable2.setModel (new VistaTabelle(rs));
            pack();
        } catch(SQLException ex) {
            DBproject.showError(this, ex);
        }
        try {
            rs=DBproject.risPart(this);
            jTable1.setModel (new VistaTabelle(rs));
            pack();
        } catch(SQLException ex) {
            DBproject.showError(this, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText1 = new javax.swing.JTextField();
        jText3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        selTab = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jText2 = new javax.swing.JTextField();
        jText4 = new javax.swing.JTextField();
        box = new javax.swing.JComboBox<>();
        jText5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jText6 = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jText1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jText1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));

        jText3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jText3.setBorder(javax.swing.BorderFactory.createTitledBorder("Data nascita (gg/mm/aaaa)"));

        jButton1.setText("Inserisci");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        selTab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "EVENTO", "SQUADRA", "GIOCATORE", "MEMBRO STAFF", "PARTITA", "TORNEO GIRONI", "TORNEO ELIMINAZIONE" }));
        selTab.setBorder(javax.swing.BorderFactory.createTitledBorder("Scegliere cosa Inserire"));
        selTab.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selTabItemStateChanged(evt);
            }
        });
        selTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selTabActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inserimento");

        jText2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cognome"));
        jText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText2ActionPerformed(evt);
            }
        });

        jText4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jText4.setBorder(javax.swing.BorderFactory.createTitledBorder("Luogo di nascita"));

        box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "'allenatore'", "'dirigente'", "'presidente'" }));
        box.setBorder(javax.swing.BorderFactory.createTitledBorder("Professione"));
        box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                boxItemStateChanged(evt);
            }
        });

        jText5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jText5.setBorder(javax.swing.BorderFactory.createTitledBorder("Nazionalità"));

        jButton2.setText("Annulla/Fine");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jText6.setBorder(javax.swing.BorderFactory.createTitledBorder("IDsquadra"));
        jText6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText6ActionPerformed(evt);
            }
        });

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Club", "Nazionale" }));
        jComboBoxTipo.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo "));
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(selTab, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jText6)
                                    .addComponent(jText4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jText5, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jText3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jText2)
                                    .addComponent(box, 0, 199, Short.MAX_VALUE)
                                    .addComponent(jComboBoxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(1, 1, 1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selTab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    String values;
    String colonne;
    ResultSet rs;
    String tipo;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            String tab=searchTab();
            if("TORNEO GIRONI".equals((String)selTab.getSelectedItem())){
                InsTornei tg = new InsTornei ();
                tg.colonne="(IDTORNEOG, IDSQUADRA)";
                tg.valori="('" + jText1.getText() + "', ";
                tg.tabella="PARTECIPANTI_GIRONI";
                tg.setVisible(true);
            }
            if("TORNEO ELIMINAZIONE".equals((String)selTab.getSelectedItem())){
                InsTornei tg = new InsTornei ();
                tg.colonne="(IDTORNEOE, IDSQUADRA)";
                tg.valori="('" + jText1.getText() + "', ";
                tg.tabella="PARTECIPANTI_ELIMINAZIONE";
                tg.setVisible(true);
            }

            String col=colonne;
            if("PARTITA".equals((String)selTab.getSelectedItem())){
                Integer index = box.getSelectedIndex();
                if (index == 1){
                    col+=", IDTORNEOG";
                }
                if (index == 2){
                    col+=", IDTORNEOE";
                }       
            }
            col+=")";
           
            String val=values;
            val=createValues();    
            try {
                DBproject.insert(tab, col, val);
                if("GIOCATORE".equals((String)selTab.getSelectedItem())){
                    String assV = "('" + jText6.getText() + "'";
                    assV+=", '" + jText1.getText() + "')";
                    String assC = "(IDSQUADRA, IDGIOCATORE)";
                    String assT = "SQUADRA_GIOCATORI";
                    DBproject.insert(assT, assC, assV);
                }
                if("PARTITA".equals((String)selTab.getSelectedItem())){
                    String assV = "('" + jText1.getText() + "', '" + jText3.getText() + "', '" + jText4.getText() + "')";
                    String assC = "(IDPARTITA, IDSQ1, IDSQ2)";
                    String assT = "INCONTRI";
                    DBproject.insert(assT, assC, assV);
                }
            }catch (SQLException ex) {
                DBproject.showError(this, ex);
            }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    private String createValues(){
        values="(";
        if(jText1.isVisible())
            values+="'" + jText1.getText() + "'";
        if(jText2.isVisible())
            values+=", '" + jText2.getText() + "'";
        if(jText3.isVisible())
            values+=", '" + jText3.getText() + "'";
        if(jText4.isVisible())
            values+=", '" + jText4.getText() + "'";
        if(jText5.isVisible()){
            if (selTab.getSelectedIndex()>2 && selTab.getSelectedIndex()<6){
                values+=", DATE '" + jText5.getText() + "'";
            }
        }
        if(jText6.isVisible()){
            if(!"GIOCATORE".equals((String)selTab.getSelectedItem())){
                values+=", '" + jText6.getText() + "'";
            }
        }
        if (box.isVisible() && !"".equals((String)box.getSelectedItem())){
            if("PARTITA".equals((String)selTab.getSelectedItem())){
                //
            }else{
                values+=", '" + (String)box.getSelectedItem() + "'";
            }
        }
        values+=")";
        return values;        
    }
    private String searchTab(){
        String tab="";
        if ("EVENTO".equals((String)selTab.getSelectedItem())){
            tab="EVENTI";
            Integer index = Integer.parseInt(jText1.getText());
            jText1.setText(index.toString());
        }
        if ("SQUADRA".equals((String)selTab.getSelectedItem())){
            tab="SQUADRA";
            Integer index = Integer.parseInt(jText1.getText());
            jText1.setText(index.toString());
        }
        if ("GIOCATORE".equals((String)selTab.getSelectedItem())){
            tab="GIOCATORE";
            Integer index = Integer.parseInt(jText1.getText());
            jText1.setText(index.toString());
        }
        if ("MEMBRO STAFF".equals((String)selTab.getSelectedItem())){
            tab="STAFF";
            Integer index = Integer.parseInt(jText1.getText());
            jText1.setText(index.toString());
        }
        if ("TORNEO GIRONI".equals((String)selTab.getSelectedItem())){
            tab="TORNEO_GIRONI";
        }
        if ("TORNEO ELIMINAZIONE".equals((String)selTab.getSelectedItem())){
            tab="TORNEO_ELIMINAZIONE";
        }
        if ("PARTITA".equals((String)selTab.getSelectedItem())){
            tab="PARTITA";
            Integer index = Integer.parseInt(jText1.getText());
            jText1.setText(index.toString());
        }
        return tab;        
    }
    
    private void selTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selTabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selTabActionPerformed

    
    private void selTabItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selTabItemStateChanged
        Integer ID = 0;
        colonne="(";
        jText1.setText("");
        jText1.setEditable(true);
        jText2.setText("");
        jText3.setText("");
        jText4.setText("");
        jComboBoxTipo.setVisible(false);
        jText5.setText("");
        jText6.setText("");
        switch(selTab.getSelectedIndex()){
            case 0:
                jText1.setVisible(false);
                jText2.setVisible(false);
                jText3.setVisible(false);
                jText4.setVisible(false);
                jText5.setVisible(false);
                jText6.setVisible(false);
                box.setVisible(false);
                break;
            case 1:
                try {
                    rs=DBproject.risPart(this);
                    System.out.println("appena andato su evento");
                    jTable1.setModel (new VistaTabelle(rs));
                    pack();
                } catch(SQLException ex) {
                    DBproject.showError(this, ex);
                }
                jText1.setVisible(true);
                jText1.setBorder(javax.swing.BorderFactory.createTitledBorder("IDevento"));
                colonne+="IDEVENTO, ";
                try {
                        ID = DBproject.calcMax("EVENTI", "IDEVENTO") +1;
                    } catch (SQLException ex) {
                        DBproject.showError(this, ex);
                    }
                jText1.setText(Integer.toString(ID));
                jText1.setEditable(false);
                jText2.setVisible(true);
                jText2.setBorder(javax.swing.BorderFactory.createTitledBorder("IDpartita"));
                colonne+="IDPARTITA, ";                
                jText3.setVisible(true);
                jText3.setBorder(javax.swing.BorderFactory.createTitledBorder("Minuto"));
                colonne+="MINUTO, ";
                jText4.setVisible(true);
                jText4.setBorder(javax.swing.BorderFactory.createTitledBorder("IDgiocatore"));
                colonne+="IDGIOCATORE, ";
                jText5.setVisible(false);
                jText6.setVisible(false);
                box.setVisible(true);
                box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Goal", "Tiri", "CartellinoG", "CartellinoR", "Fuorigioco", "Assist", "TiroInPorta" }));
                box.setBorder(javax.swing.BorderFactory.createTitledBorder("Evento"));
                colonne+="EVENTO";
                break;
            case 2:
                jText1.setVisible(true);
                jText1.setBorder(javax.swing.BorderFactory.createTitledBorder("IDsquadra"));
                colonne+="IDSQUADRA, ";
                try {
                        ID = DBproject.calcMax("SQUADRA", "IDSQUADRA") + 1;
                    } catch (SQLException ex) {
                        DBproject.showError(this, ex);
                    }
                jText1.setText(Integer.toString(ID));
                jText1.setEditable(false);
                jText2.setVisible(true);
                jText2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
                colonne+="NOME, ";
                jText3.setVisible(false);
                jText4.setVisible(false);
                jText5.setVisible(false);
                jText6.setVisible(false);
                box.setVisible(true);
                box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "club", "nazionale"}));
                colonne+="TIPO";
                box.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Squadra"));
                break;
            case 3:
                jComboBoxTipo.setVisible(true);
                tipo=(String) jComboBoxTipo.getSelectedItem();
                try {
                    rs=DBproject.ricSqT(this, tipo);
                    jTable1.setModel (new VistaTabelle(rs));
                    pack();
                } catch(SQLException ex) {
                    DBproject.showError(this, ex);
                }
                
                jText1.setVisible(true);
                jText1.setBorder(javax.swing.BorderFactory.createTitledBorder("IDgiocatore"));
                colonne+="IDGIOCATORE, ";
                try {
                        ID = DBproject.calcMax("GIOCATORE", "IDGIOCATORE") + 1;
                    } catch (SQLException ex) {
                        DBproject.showError(this, ex);
                    }
                jText1.setText(Integer.toString(ID));
                jText1.setEditable(false);
                jText2.setVisible(true);
                jText2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
                colonne+="NOME, ";
                jText3.setVisible(true);
                jText3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cognome"));
                colonne+="COGNOME, ";
                jText6.setVisible(true);
                jText6.setBorder(javax.swing.BorderFactory.createTitledBorder("ID squadra di riferimento"));
                box.setVisible(true);
                box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "portiere", "difensore", "centrocampista", "attaccante"}));
                box.setBorder(javax.swing.BorderFactory.createTitledBorder("Ruolo"));
                colonne+="RUOLO";
                break;
            case 4:
                jComboBoxTipo.setVisible(true);
                tipo=(String) jComboBoxTipo.getSelectedItem();
                try {
                    rs=DBproject.ricSqT(this, tipo);
                    jTable1.setModel (new VistaTabelle(rs));
                    pack();
                } catch(SQLException ex) {
                    DBproject.showError(this, ex);
                }
                jText1.setVisible(true);
                jText1.setBorder(javax.swing.BorderFactory.createTitledBorder("IDstaff"));
                colonne+="IDSTAFF, ";
                try {
                        ID = DBproject.calcMax("STAFF", "IDSTAFF") + 1;
                    } catch (SQLException ex) {
                        DBproject.showError(this, ex);
                    }
                jText1.setText(Integer.toString(ID));
                jText1.setEditable(false);
                jText2.setVisible(true);
                jText2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome"));
                colonne+="NOME, ";
                jText3.setVisible(true);
                jText3.setBorder(javax.swing.BorderFactory.createTitledBorder("Cognome"));
                colonne+="COGNOME, ";
                jText4.setVisible(true);
                jText4.setBorder(javax.swing.BorderFactory.createTitledBorder("Luogo di Nascita"));
                colonne+="LUOGONASCITA, ";
                jText5.setVisible(true);
                jText5.setBorder(javax.swing.BorderFactory.createTitledBorder("Data di Nascita (aaaa-mm-gg)"));
                colonne+="DATANASCITA, ";
                jText6.setVisible(true);
                jText6.setBorder(javax.swing.BorderFactory.createTitledBorder("IDsquadra"));
                colonne+="IDSQUADRA, ";
                box.setVisible(true);
                box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "allenatore", "dirigente", "presidente"}));
                box.setBorder(javax.swing.BorderFactory.createTitledBorder("Professione"));
                colonne+="PROFESSIONE";
                break;
            case 5:
                //partite
                jComboBoxTipo.setVisible(true);
                tipo=(String) jComboBoxTipo.getSelectedItem();
                try {
                    rs=DBproject.ricSqT(this, tipo);
                    jTable1.setModel (new VistaTabelle(rs));
                    pack();
                } catch(SQLException ex) {
                    DBproject.showError(this, ex);
                }
                jText1.setVisible(true);
                jText1.setBorder(javax.swing.BorderFactory.createTitledBorder("IDpartita"));
                colonne+="IDPARTITA, ";
                try {
                        ID = DBproject.calcMax("PARTITA", "IDPARTITA")+1;
                    } catch (SQLException ex) {
                        DBproject.showError(this, ex);
                    }
                jText1.setText(Integer.toString(ID));
                jText1.setEditable(false);
                jText2.setVisible(true);
                jText2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stadio"));
                colonne+="STADIO, ";
                jText3.setVisible(true);
                jText3.setBorder(javax.swing.BorderFactory.createTitledBorder("IDsquadra 1"));
                colonne+="IDSQ1, ";
                jText4.setVisible(true);
                jText4.setBorder(javax.swing.BorderFactory.createTitledBorder("IDsquadra 2"));
                colonne+="IDSQ2, ";
                jText5.setVisible(true);
                jText5.setBorder(javax.swing.BorderFactory.createTitledBorder("Data (aaaa-mm-gg)"));
                colonne+="DATA";
                jText6.setVisible(true);
                jText6.setBorder(javax.swing.BorderFactory.createTitledBorder("ID del torneo"));
                box.setVisible(true);
                box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Torneo a Gironi", "Torneo ad Eliminazione"}));
                box.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo di Torneo"));
                /*int index = box.getSelectedIndex();
                if (index == 1) 
                    colonne+=", IDTORNEOG";
                if (index == 2)
                    colonne+=", IDTORNEOE";*/
                break;
            case 6:
                //torneo gironi
                jText1.setVisible(true);
                jText1.setBorder(javax.swing.BorderFactory.createTitledBorder("IDtorneo girone"));
                colonne+="IDTORNEOG, ";
                jText2.setVisible(true);
                jText2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stagione"));
                colonne+="STAGIONEG, ";
                jText3.setVisible(true);
                jText3.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome Torneo"));
                colonne+="NOMETORNEOG";
                jText4.setVisible(false);
                jText5.setVisible(false);
                jText6.setVisible(false);
                box.setVisible(false);
                break;
            case 7:
                //torneo eliminazione
                jText1.setVisible(true);
                jText1.setBorder(javax.swing.BorderFactory.createTitledBorder("IDtorneo eliminazione"));
                colonne+="IDTORNEOE, ";
                jText2.setVisible(true);
                jText2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stagione"));
                colonne+="STAGIONEE, ";
                jText3.setVisible(true);
                jText3.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome Torneo"));
                colonne+="NOMETORNEOE";
                jText4.setVisible(false);
                jText5.setVisible(false);
                jText6.setVisible(false);
                box.setVisible(false);
                break;                
        }
    }//GEN-LAST:event_selTabItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void boxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_boxItemStateChanged
        if("Torneo a gironi".equals((String)box.getSelectedItem()) || "Torneo ad Eminazione".equals((String)selTab.getSelectedItem())){
            jText6.setEditable(true);   
        }
    }//GEN-LAST:event_boxItemStateChanged

    private void jText6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText6ActionPerformed

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged
        ResultSet rs;
        String tipo= (String) jComboBoxTipo.getSelectedItem();
        try {
            rs=DBproject.ricSqT(this, tipo);
            jTable1.setModel (new VistaTabelle(rs));
            pack();
        } catch(SQLException ex) {
            DBproject.showError(this, ex);
        }
    }//GEN-LAST:event_jComboBoxTipoItemStateChanged

    private void jText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Insert().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jText1;
    private javax.swing.JTextField jText2;
    private javax.swing.JTextField jText3;
    private javax.swing.JTextField jText4;
    private javax.swing.JTextField jText5;
    private javax.swing.JTextField jText6;
    private javax.swing.JComboBox<String> selTab;
    // End of variables declaration//GEN-END:variables
}
